# name: Deploy

# on:
#   workflow_run:
#     workflows: ["Build"]
#     types:
#       - completed

# jobs:
#   deploy:
#     runs-on: self-hosted

#     steps:
#       - name: Download Artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: csharp-artifact
#           path: ./output

#       - name: Upload to deploy directory
#         run: |
#           mkdir -p /home/azubi/deploy/csharp-app/
#           cp -r ./output/* /home/azubi/deploy/csharp-app/