name: Deploy
 
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
 
jobs:
  build-and-run:
    runs-on: self-hosted
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Upload to deploy directory
        run: |
          mkdir -p /home/azubi/deploy/csharp-app/
          cp -r output/* /home/azubi/deploy/csharp-app/