name: Build

on:
  push:
    branches: [main]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore and Publish Project
        run: |
          /home/azubi/.dotnet/dotnet restore 01_CI_CD_Pipes_Uebung/01_CI_CD_Pipes_Uebung.csproj
          /home/azubi/.dotnet/dotnet publish 01_CI_CD_Pipes_Uebung/01_CI_CD_Pipes_Uebung.csproj -c Release --no-restore -o ./output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: csharp-app
          path: ./output