name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Projects
        run: |
          /home/azubi/.dotnet/dotnet restore 01_CI_CD_Pipes_Uebung/01_CI_CD_Pipes_Uebung.csproj
          /home/azubi/.dotnet/dotnet restore 01_CI_CD_Pipes_Uebung.Tests/01_CI_CD_Pipes_Uebung.Tests.csproj

      - name: Run Unit Tests
        run: |
          /home/azubi/.dotnet/dotnet test 01_CI_CD_Pipes_Uebung.Tests/01_CI_CD_Pipes_Uebung.Tests.csproj --no-restore --verbosity normal

      - name: Publish Project
        run:
          /home/azubi/.dotnet/dotnet publish 01_CI_CD_Pipes_Uebung/01_CI_CD_Pipes_Uebung.csproj -c Release --no-restore -o ./output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: csharp-artifact
          path: ./output


  deploy:
    needs: build-and-test
    runs-on: self-hosted

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: csharp-artifact
          path: ./output

      - name: Upload to deploy directory
        run: |
          mkdir -p /home/azubi/deploy/csharp-app/
          cp -r ./output/* /home/azubi/deploy/csharp-app/
